export const BUILDER_DATA_SOURCES = {
  QLD_QBCC_LICENSED_CONTRACTORS: {
    id: "QLD_QBCC_LICENSED_CONTRACTORS",
    state: "QLD",
    source: "QBCC",
    type: "ckan_datastore",
    name: "QBCC register of licensed builders and contractors",
    url: "https://www.data.qld.gov.au/dataset/qbcc-licensed-contractors-register/resource/25608781-b28c-44f8-8545-0ab18d84082f",
    apiUrl: "https://www.data.qld.gov.au/api/3/action/datastore_search",
    resourceId: "25608781-b28c-44f8-8545-0ab18d84082f",
    licence: "Queensland Government open data",
    notes: "Includes licensed builders, trade contractors, designers, nominees, site supervisors and occupational licence holders. Dwella filters to builder licence classes.",
  },
  NSW_FAIR_TRADING_CONTRACTOR_LICENCE: {
    id: "NSW_FAIR_TRADING_CONTRACTOR_LICENCE",
    state: "NSW",
    source: "NSW_FAIR_TRADING",
    type: "xlsx_download",
    name: "Current Licence Extract - Contractor Licence",
    url: "https://data.nsw.gov.au/data/dataset/home-building-licensing/resource/423b6102-fe3f-45d5-a805-a0d5eb3578d1",
    downloadUrl: "https://www.onegov.nsw.gov.au/agencies/oft/Contractor%20Licence.xlsx",
    licence: "Creative Commons Attribution",
    notes: "Official NSW contractor licence extract workbook. Dwella reads licensee sheets and filters to builder classes.",
  },
  VIC_BPC_REGISTER: {
    id: "VIC_BPC_REGISTER",
    state: "VIC",
    source: "BPC_VIC",
    type: "csv_download",
    name: "BPC Building Practitioner Register",
    url: "https://discover.data.vic.gov.au/dataset/bpc-building-practitioner-register/resource/3599fa1f-29f3-417e-8679-1842e2e6e2df",
    downloadUrl: "https://vicopendatavba.blob.core.windows.net/vicopendata/BPR.csv",
    licence: "other-closed",
    notes: "Official DataVic BPC Building Practitioner Register CSV. Dwella filters to builder classes and skips records without a published account name.",
  },
  SA_CBS_LICENCE_REGISTER: {
    id: "SA_CBS_LICENCE_REGISTER",
    state: "SA",
    source: "SA_CBS",
    type: "manual_connector_required",
    name: "Consumer and Business Services licence register",
    url: "https://www.sa.gov.au/topics/business-and-trade/licensing/licence-check",
    searchUrl: "https://secure.cbs.sa.gov.au/OccLicPubReg/index.php",
    accessStatus: "blocked_by_public_search_recaptcha",
    accessRequestContact: {
      agency: "Consumer and Business Services South Australia",
      email: "occupational@sa.gov.au",
      phone: "131 882",
      url: "https://www.sa.gov.au/topics/business-and-trade/licensing/building-and-trades/renew-your-licence",
      evidenceUrl: "https://www.sa.gov.au/topics/business-and-trade/licensing/building-and-trades/renew-your-licence",
    },
    accessEvidence: [
      {
        checkedAt: "2026-06-29",
        url: "https://www.cbs.sa.gov.au/find-a-licence-holder",
        finding: "Official CBS page confirms the licensing register can be searched for work or business licence holders including builders, but it links to the protected public register and does not expose a sanctioned bulk extract or documented API.",
        importDecision: "not_used_for_import",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://www.sa.gov.au/topics/business-and-trade/licensing/licence-check",
        finding: "SA.GOV.AU confirms the occupational licence register covers builders and can be searched by licence number, surname or trading name; no bulk per-builder extract or documented API is published on the page.",
        importDecision: "not_used_for_import",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://secure.cbs.sa.gov.au/OccLicPubReg/index.php",
        finding: "Public occupational register lookup is protected by reCAPTCHA.",
        importDecision: "pending_sanctioned_bulk_extract_or_api",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://data.sa.gov.au/data/api/3/action/package_show?id=occupational-licences",
        finding: "Data.SA CKAN API exposes the Occupational Licences package, but resources are historical snapshots ending in September 2018 and package metadata was last modified in 2019; not a current production register.",
        importDecision: "rejected_stale_snapshot",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://data.sa.gov.au/data/dataset/d8e12b1f-2abf-44e4-9531-6f19cc61144b",
        finding: "CBS Annual Report Building Work Contractors resource contains aggregate counts, not per-builder licence records.",
        importDecision: "rejected_aggregate_only",
      },
    ],
    notes: "Connector pending. The public occupational register search is protected by reCAPTCHA, so Dwella does not automate it without a sanctioned bulk extract/API.",
  },
  WA_BUILDING_ENERGY_REGISTER: {
    id: "WA_BUILDING_ENERGY_REGISTER",
    state: "WA",
    source: "WA_BUILDING_ENERGY",
    type: "pdf_download",
    name: "Register of builders",
    url: "https://www.wa.gov.au/service/community-services/find-registered-builder",
    downloadUrl: "https://contenthub.demirs.wa.gov.au/downloads/cals/BuilderRegister.pdf",
    notes: "Official WA register of building contractors and practitioners. Dwella imports Section 1 current building contractors only.",
  },
  ACT_ACCESS_CANBERRA_REGISTER: {
    id: "ACT_ACCESS_CANBERRA_REGISTER",
    state: "ACT",
    source: "ACT_ACCESS_CANBERRA",
    type: "socrata_api",
    name: "Access Canberra List of Professionals",
    url: "https://www.data.act.gov.au/Business-and-Industry/List-of-Professionals/de4w-gbt3",
    apiUrl: "https://www.data.act.gov.au/resource/de4w-gbt3.json",
    searchUrl: "https://www.accesscanberra.act.gov.au/app/services/licence/",
    accessEvidence: [
      {
        checkedAt: "2026-06-29",
        url: "https://www.data.act.gov.au/Business-and-Industry/List-of-Professionals/de4w-gbt3",
        finding: "Official ACT Government open data dataset lists licensed, registered or accredited design and construction professionals and is updated daily.",
        importDecision: "imported_official_open_data",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://www.data.act.gov.au/resource/de4w-gbt3.json",
        finding: "Socrata API exposes current rows with occupation, description/class, COLA licence number, ACN, expiry date and licence status.",
        importDecision: "imported_official_open_data_api",
      },
    ],
    notes: "Official ACT Government Socrata dataset. Dwella imports active Builder occupation rows and excludes Owner Builder records.",
  },
  TAS_CBOS_REGISTER: {
    id: "TAS_CBOS_REGISTER",
    state: "TAS",
    source: "TAS_CBOS",
    type: "manual_connector_required",
    name: "CBOS licensed occupations search",
    url: "https://www.cbos.tas.gov.au/topics/licensing-and-registration/search-licensed-occupations/find-a-licensed-tradesperson",
    searchUrl: "https://occupationallicensing.justice.tas.gov.au/Search/onlinesearch.aspx",
    accessStatus: "blocked_by_public_search_recaptcha",
    accessRequestContact: {
      agency: "Consumer, Building and Occupational Services Tasmania",
      email: "CBOS.info@justice.tas.gov.au",
      phone: "1300 654 499",
      url: "https://cbos.tas.gov.au/contact-us",
      evidenceUrl: "https://cbos.tas.gov.au/contact-us",
    },
    accessEvidence: [
      {
        checkedAt: "2026-06-29",
        url: "https://occupationallicensing.justice.tas.gov.au/Search/onlinesearch.aspx",
        finding: "CBOS WebForms occupational licensing search exposes builder filters but protects result search with Google reCAPTCHA.",
        importDecision: "pending_sanctioned_bulk_extract_or_api",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://www.cbos.tas.gov.au/topics/licensing-and-registration/search-licensed-occupations/find-a-licensed-tradesperson",
        finding: "Official CBOS page points users to the licensed occupations search for trades and building services providers; no sanctioned bulk extract or documented API is published on the page.",
        importDecision: "not_used_for_import",
      },
      {
        checkedAt: "2026-06-29",
        url: "https://data.gov.au/data/api/3/action/package_show?id=trade-licensing",
        finding: "data.gov.au Trade Licensing package contains point-in-time 2016/2017 Department of Justice occupational licensing extracts and aggregate-style metadata, not a current per-builder production register.",
        importDecision: "rejected_stale_snapshot",
      },
    ],
    notes: "Connector pending. The public WebForms register exposes builder filters, but result search is protected by Google reCAPTCHA, so Dwella does not automate it without sanctioned access.",
  },
  NT_BPB_REGISTER: {
    id: "NT_BPB_REGISTER",
    state: "NT",
    source: "NT_BPB",
    type: "html_register",
    name: "NT Public Register of Building Practitioners",
    url: "https://www.ntlis.nt.gov.au/building-practitioners/",
    searchUrl: "https://www.ntlis.nt.gov.au/building-practitioners/results.jsp",
    detailBaseUrl: "https://www.ntlis.nt.gov.au/building-practitioners/",
    categories: ["CR", "CU", "ZR", "ZU"],
    notes: "Official NT public register. Dwella imports ACTIVE residential and commercial building contractor categories.",
  },
};

export function listBuilderDataSources() {
  return Object.values(BUILDER_DATA_SOURCES);
}
