export const DWELLA_TABLE_SCHEMAS = {
  builders: {
    name: "string",
    tradingNames: "string[]",
    websiteUrl: "string?",
    abn: "string?",
    acn: "string?",
    states: "AustralianState[]",
    serviceRegions: "string[]",
    builderType: '"custom" | "project" | "volume" | "luxury" | "renovation" | "knockdown_rebuild" | "unknown"',
    homeTypes: "string[]",
    priceTier: '"entry" | "mid" | "premium" | "luxury" | "unknown"',
    priceEvidence: "string?",
    status: '"active" | "unverified" | "hidden" | "do_not_contact"',
    lastEnrichedAt: "number?",
    createdAt: "number",
    updatedAt: "number",
  },
  builderLicences: {
    builderId: 'Id<"builders">',
    source: '"QBCC" | "NSW_FAIR_TRADING" | "BPC_VIC" | "SA_CBS" | "WA_BUILDING_ENERGY" | "ACT_ACCESS_CANBERRA" | "TAS_CBOS" | "NT_BPB"',
    state: "AustralianState",
    licenceNumber: "string",
    licenceClass: "string?",
    licenceType: "string?",
    status: "string?",
    restrictions: "string[]?",
    rawSourceUrl: "string?",
    lastCheckedAt: "number",
    confidence: "number",
  },
  builderWebsiteSnapshots: {
    builderId: 'Id<"builders">',
    url: "string",
    title: "string?",
    rawTextStorageId: 'Id<"_storage">?',
    extractedSummary: "string",
    extractedCapabilities: "BuilderCapabilities",
    priceSignals: "PriceSignals",
    contactDetails: "BuilderContactDetails",
    lastCrawledAt: "number",
    confidence: "number",
  },
  builderMemoryCards: {
    builderId: 'Id<"builders">',
    markdown: "string",
    searchableText: "string",
    sourceIds: "string[]",
    lastGeneratedAt: "number",
    confidence: "number",
    ragNamespace: "string",
  },
  builderContactEvents: {
    builderId: 'Id<"builders">',
    projectId: 'Id<"projects">',
    type: '"drafted" | "approved" | "sent" | "opened" | "replied" | "followed_up" | "declined" | "quote_received"',
    channel: '"email" | "phone" | "form" | "sms"',
    localTimeZone: "string",
    occurredAt: "number",
    summary: "string",
    payloadHash: "string?",
  },
};

export const CONVEX_ARCHITECTURE_CONTRACT = {
  durableMemory: "Convex AI Agent component",
  builderSearch: "Convex RAG component with builderMemoryCards as the source of searchable truth",
  longRunningJobs: "Convex Workflow component",
  realtimeToolAccess: "Convex MCP Gateway with auth, scopes and audit logging",
  documentStorage: "Convex File Storage",
  rateLimits: "Convex Rate Limiter",
};
